version: '3.1'
services:
  wp:
    image: mahype/wordpress:latest
    environment:
      MYSQL_HOST: db
      MYSQL_DB: wp
      MYSQL_USER: root
      MYSQL_PASS: p4ssw0rd!
      WP_VERSION: 4.9.0
      WP_LOCALE: en_US
      WP_USER: admin
      WP_PASS: password
      WP_URL: torro-forms.dev
      WP_INSTALL: "fresh"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
      - php
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: mahype/phpbrew:latest
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      PHP_VERSION: "7.1.8"
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
  behat:
    image: mahype/wordhat:latest
    volumes:
      - ./:/src
    # Run a built-in web server for access to HTML reports
    ports:
      - 8081:8000
    entrypoint: "php -S 0.0.0.0:8000"
  browser:
    image: selenium/standalone-chrome
volumes:
  dbdata:
