version: '3.2'
services:
  wp:
    image: mahype/wordpress:latest
    environment:
      MYSQL_HOST: db
      MYSQL_DB: website
      MYSQL_USER: root
      MYSQL_PASS: root
      WP_VERSION: 5.0.3
      WP_LOCALE: en_US
      WP_USER: admin
      WP_PASS: password
      WP_URL: ${LOCAL_HOST}
    volumes:
      - ./www:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/plugin:ro
    depends_on:
      - db
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/plugin:ro
    depends_on:
      - wp
  php:
    build: ./conf/php
    volumes:
      - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./www:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/plugin:ro
    depends_on:
      - wp
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8080:80
  mailcatcher:
    image: mailhog/mailhog
    ports:
    - 1030:1025
    - 8025:8025
volumes:
  database: